create table departements (id bigint not null auto_increment, description varchar(500), email varchar(100), nom varchar(100) not null, telephone varchar(20), primary key (id)) engine=InnoDB;
create table incident (id bigint not null auto_increment, date_declaration datetime(6), date_derniere_miseajour datetime(6), date_resolution datetime(6), date_resolution_estimee datetime(6), description varchar(255), latitude double precision, longitude double precision, priorite varchar(255), statut varchar(255), agent_id bigint, citoyen_id bigint, departement_id bigint not null, quartier_id bigint not null, service_id bigint, primary key (id)) engine=InnoDB;
create table log_entry (id bigint not null auto_increment, action varchar(255), ip_address varchar(255), level varchar(255), message varchar(255), timestamp datetime(6), username varchar(255), primary key (id)) engine=InnoDB;
create table notification (id bigint not null auto_increment, date_envoi datetime(6), lu bit not null, message varchar(255), type varchar(255), incident_id bigint, utilisateur_id bigint, primary key (id)) engine=InnoDB;
create table photo (id bigint not null auto_increment, chemin_stockage varchar(255), date_upload datetime(6), nom_fichier varchar(255), principale bit not null, type_contenu varchar(255), incident_id bigint, primary key (id)) engine=InnoDB;
create table preference_notification (id bigint not null auto_increment, email_actif bit not null, email_changement_statut bit not null, push_actif bit not null, utilisateur_id bigint not null, primary key (id)) engine=InnoDB;
create table quartier (id bigint not null auto_increment, code_postal varchar(4) not null, nom varchar(100) not null, departement_id bigint, primary key (id)) engine=InnoDB;
create table rapport (id bigint not null auto_increment, chemin_fichier varchar(255) not null, date_debut date not null, date_fin date not null, date_generation datetime(6) not null, delai_moyen double precision, format varchar(255) not null, incidents_en_cours bigint, incidents_resolus bigint, nom_fichier varchar(255) not null, taille_fichier bigint, titre varchar(255) not null, total_incidents bigint, departement_id bigint, genere_par bigint, quartier_id bigint, service_id bigint, primary key (id)) engine=InnoDB;
create table service_municipal (id bigint not null auto_increment, description varchar(500), nom varchar(100) not null, departement_id bigint not null, primary key (id)) engine=InnoDB;
create table utilisateur (id bigint not null auto_increment, auth_provider varchar(255), email varchar(255), email_verifie bit not null, image_url varchar(255), mot_de_passe varchar(255), nom varchar(255), prenom varchar(255), provider_id varchar(255), role varchar(255), verification_token varchar(255), verification_token_expiration datetime(6), departement_id bigint, service_municipal_id bigint, primary key (id)) engine=InnoDB;
alter table departements add constraint UK_o7gxpwc0wow8fsm1u9ox55f01 unique (nom);
alter table preference_notification add constraint UK_469xc9b2avh2fjoaumlx0e3s7 unique (utilisateur_id);
alter table quartier add constraint UK_9d21ih06bhaa664ywvgw8g7hj unique (nom);
alter table utilisateur add constraint UK_rma38wvnqfaf66vvmi57c71lo unique (email);
alter table incident add constraint FKg8fm0ov8lnyauuv5ylur1ck7s foreign key (agent_id) references utilisateur (id);
alter table incident add constraint FKujrr7j3golvt6447kp5wa9yy foreign key (citoyen_id) references utilisateur (id);
alter table incident add constraint FK68xigmjbr3y8xkcfi0sxadaa9 foreign key (departement_id) references departements (id);
alter table incident add constraint FKc0w7ern2js7hcdx6ba49nhy84 foreign key (quartier_id) references quartier (id);
alter table incident add constraint FKaowuia1i7by1424bw2kxa4mb1 foreign key (service_id) references service_municipal (id);
alter table notification add constraint FKi00oe9rhur9n8n8r3cm7elov2 foreign key (incident_id) references incident (id);
alter table notification add constraint FK1e85ddpswdf3uq1oaklnjiucf foreign key (utilisateur_id) references utilisateur (id);
alter table photo add constraint FK308pg4rjq6raet1iat1mp28kf foreign key (incident_id) references incident (id);
alter table preference_notification add constraint FKpr1jvgy5sa56n4whb5tow3970 foreign key (utilisateur_id) references utilisateur (id);
alter table quartier add constraint FKqktohdevm4c96qn96tqcpj4td foreign key (departement_id) references departements (id);
alter table rapport add constraint FKc4e028m0cwip4ixfb2h94al3l foreign key (departement_id) references departements (id);
alter table rapport add constraint FK6spxh18wsjap81tcr0nadx5vl foreign key (genere_par) references utilisateur (id);
alter table rapport add constraint FKrsjxblfqdvrgpnw8ep4hu68y5 foreign key (quartier_id) references quartier (id);
alter table rapport add constraint FK2k0cs6en17jm3r6aukwoh9fb1 foreign key (service_id) references service_municipal (id);
alter table service_municipal add constraint FKdyqi64ajnlrv2bhp4vwle9r5u foreign key (departement_id) references departements (id);
alter table utilisateur add constraint FK449mrh7cxlixxep0u7shtbntg foreign key (departement_id) references departements (id);
alter table utilisateur add constraint FK7edhj67umk9t4qvyve4jpnvpx foreign key (service_municipal_id) references service_municipal (id);
